image: ruby:2.2.0
services:
  - postgres
before_script:
  - apt-get update -qq && apt-get install -y -qq postgresql postgresql-contrib libpq-dev cmake
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc
  - bundle install --without staging production

stages:
  - build
  - deploytest

build:
  stage: build
  script:
    - PADRINO_ENV=test bundle exec rake