language: ruby
rvm:
  - 2.2.0
bundler_args: --without development staging production
before_script:
- sh -e /etc/init.d/xvfb start
script: PADRINO_ENV=travis bundle exec padrino rake

notifications:
  email:
    - camilagarcia.113@gmail.com
    - jfflores90@gmail.com
    - cravacuore24@gmail.com
    - santiagoladavaz@gmail.com
